### ISSUE TITLE
Available on windows desktop ?

### ISSUE THREAD

**Issue by iremceliksena** [minaxorg/flutter_intro#10]
Hi, I'm trying to use this package as a desktop application, but I couldn't get it to work. However, I ran it in the mobile application. Then I saw that there is no web support in flutter 3, I wonder if it is not available for desktop applications at the moment?

**Comment by hellohejinyu** [comment]
In fact, this library does not use any native platform code and relies entirely on the implementation of the Flutter layer. Therefore, if the official Flutter perfectly adapts to all platforms, then it should work properly.
