### ISSUE TITLE
StatelessWidget and Statefulwidget

### ISSUE THREAD

**Issue by NathanFlorins** [minaxorg/flutter_intro#11]
Can this work in stateless widget ? Or only stateful? 
I have this error  : 
E/flutter ( 7192): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FlutterIntroException: The context does not contain an Intro widget.
E/flutter ( 7192): #0      Intro.of (package:flutter_intro/flutter_intro.dart:389:7)
E/flutter ( 7192): #1      _IntroStepBuilderState.initState.<anonymous closure> (package:flutter_intro/intro_step_builder.dart:60:34)
E/flutter ( 7192): #2      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
E/flutter ( 7192): #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 7192): #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7192): #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7192): #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
E/flutter ( 7192):

**Comment by hellohejinyu** [comment]
![image](https://github.com/minaxorg/flutter_intro/assets/8766034/d869b8c9-5e3a-4ed7-84e6-2cdadfee7f89)

StatelessWidget also works normally, please check the sample code in the project example
