### ISSUE TITLE
different dart file make a page can not work intro

### ISSUE THREAD

**Issue by AKA-LinCoder** [minaxorg/flutter_intro#13]
i have a page in different dart file, i use intro in these file ,it can not work

**Comment by AKA-LinCoder** [comment]
i want to wait home view is loaded ,after that show intro on floatbutton,but i can not be

**Comment by alireza-hnzpv** [comment]
same problem

**Comment by hellohejinyu** [comment]
https://github.com/hellohejinyu/intro_different_page

https://github.com/minaxorg/flutter_intro/assets/8766034/66019919-4a3e-4abb-af1c-e7cf2dcfcfcb

I wrote a demo. Common is a public component, which is in page1 and page2. Page1 and page2 each hold an intro instance.
I don't know if it can solve your problem

**Comment by AKA-LinCoder** [comment]
nfg
