### ISSUE TITLE
IntroStepBuilder across pages and highlighting a bottom nav bar icon

### ISSUE THREAD

**Issue by xxJeevesxx** [minaxorg/flutter_intro#14]
I'm using a bottom nav bar, specifically this https://pub.dev/packages/persistent_bottom_nav_bar_v2 and I'm wondering if it's possible to set this up so that on first load to highlight one of the bottom bar icons, then the user can click next which will navigate to a different page and highlight something else. like a completel tutorial or walk through of my app?

**Comment by hellohejinyu** [comment]
https://github.com/minaxorg/flutter_intro/assets/8766034/fd6c939f-7319-43ef-927d-fa784e77db18

If this is the effect you want, it can be achieved. I added some code to the example of `persistent_bottom_nav_bar_v2`. You can refer to it.

https://github.com/hellohejinyu/cross_page_intro/commit/ad111c4ca42d1c8adaa5aed47fff159c8da8d5e9

**Comment by xxJeevesxx** [comment]
Thanks for the quick reply. Looks great, not sure how I couldn't come up with that. Thanks!
