### ISSUE TITLE
Issue with Library on Android Web - Introstep Highlighting and Background Darkening Not Working

### ISSUE THREAD

**Issue by alicjat** [minaxorg/flutter_intro#16]
Hi,
I am encountering an issue when using the library on Android Web. When running the application on a web browser on an Android phone, the introstep feature does not work as expected. The element is not highlighted, and the background is not darkened, making the text unreadable. Interestingly, the issue seems to be specific to Android devices, as it works flawlessly on other platforms. Screenshots from an iPhone 12 Pro show the correct behavior, while those from a Pixel 6 do not.

<img width="414" alt="Zrzut ekranu 2024-01-11 161430" src="https://github.com/minaxorg/flutter_intro/assets/88663454/ecf65f50-76af-4298-aa05-62eb3334759a">
<img width="398" alt="Zrzut ekranu 2024-01-11 161450" src="https://github.com/minaxorg/flutter_intro/assets/88663454/dead2aae-f15e-49ab-85d1-d23c68d0fd92">

**Comment by hellohejinyu** [comment]
This is an issue with Flutter; their support for the Web platform is not yet fully developed.
