### ISSUE TITLE
[Suggestion] Allow more IntroButton customization

### ISSUE THREAD

**Issue by EnduringBeta** [minaxorg/flutter_intro#24]
I find the font size for the default `IntroStepBuilder` to be too small. I am glad I can customize with `overlayBuilder` where I followed an example in the repo.

I wish I could use `IntroButton`, but very little customization is allowed for that class. Size, font size, and color would be great.

For now I'm building my own.

**Comment by hellohejinyu** [comment]
Thank you, you are absolutely right, I have also seen your PR, I will review and merge it as soon as possible. Thank you for making this package better.
