### ISSUE TITLE
Customize the width or make the width take the full size

### ISSUE THREAD

**Issue by michaeledrian** [minaxorg/flutter_intro#27]
Can the width be customized in the _StepWidgetBuilder or make the width become as large as possible?
right now the width is limited (if I understand correctly, in the code it is forced to not take full width inside the _StepWidgetBuilder)

**Comment by hellohejinyu** [comment]
![image](https://github.com/user-attachments/assets/ca3cd7f1-7e25-4cb5-991c-63182fe32a98)

https://github.com/minaxorg/flutter_intro/blob/148e6c8e386ea6c93721230ee841e257f7ebf201/example/lib/advanced_usage.dart#L41-L51

**Comment by michaeledrian** [comment]
Thanks!
I will try it this week!
