### ISSUE TITLE
Hide Next button 

### ISSUE THREAD

**Issue by azazadev** [minaxorg/flutter_intro#3]
it's possible to hide next button ?

**Comment by ahmadbilal55** [comment]
You can use overlayBuilder parameter to define custom overlay and hide the next button.

`
            IntroStepBuilder(
              order: 4,
              text: 'Hello this is my intro 4',
              padding: EdgeInsets.zero,
              overlayBuilder: (params)=>ColoredBox(color: Colors.black.withOpacity(0.3)),
              builder: (context, key) => SizedBox(height: 30,width: 30,)
            )`

**Comment by hellohejinyu** [comment]
Please check the sample code of the project for detailed usage instructions.
