### ISSUE TITLE
Migration document from v2 to 3

### ISSUE THREAD

**Issue by absar** [minaxorg/flutter_intro#4]
@hellohejinyu please create a migration document from v2 to 3, the example and readme are not very intuitive.

**Comment by hellohejinyu** [comment]
2 and 3 are completely different projects, and the usage methods are also completely different (the purpose is to solve some previous unresolved issues, such as the guidance of dynamically generated components). If version 2 can be used normally, it is completely fine. You can keep using it without upgrading.
