### ISSUE TITLE
How to initialize a second intro sequence on the same page?

### ISSUE THREAD

**Issue by ShahoodulHassan** [minaxorg/flutter_intro#5]
Hi,

Thanks for this nice package!

I just wanted to know how to initialize the `Intro` if we plan to start a second intro sequence (the first being on app launch) on the same Page, only after the user performs an operation or presses a button.

How would both `Intro` objects differentiate between each other's step order number 1?

Thanks!

**Comment by ZhenHao1998** [comment]
@ShahoodulHassan any solution on your side? The owner of this repo seems inactive.

**Comment by ShahoodulHassan** [comment]
Sorry, I don't think it is possible with this package.

**Comment by hellohejinyu** [comment]
<img src="https://raw.githubusercontent.com/minaxorg/flutter_intro/master/doc/v3/example3.gif" width="300" />

Grouping can now be done using `group` in `IntroStepBuilder`,then pass in the group you want to start in the `start` method.
