### ISSUE TITLE
Global Key issue

### ISSUE THREAD

**Issue by jaydeepktridhya** [minaxorg/flutter_intro#8]
I am getting Multiple Global Key issues in my app when I try to show 2 or 3 IntroStepBuilder.

**Comment by jaydeepktridhya** [comment]
The key [GlobalObjectKey int#00001] was used by multiple widgets. The parents of those widgets were:
- IntroStepBuilder(dependencies: [Intro], state: _IntroStepBuilderState#57d6b)
- IntroStepBuilder(dependencies: [Intro], state: _IntroStepBuilderState#427d2)
A GlobalKey can only be specified on one widget at a time in the widget tree.

**Comment by frankenten13** [comment]
Same issue

**Comment by BLB-EN438** [comment]
Any updates here?

**Comment by johnkreagan** [comment]
Same issue here, it's causing somewhat significant issues in our testing.

**Comment by yugin21** [comment]
> I am getting Multiple Global Key issues in my app when I try to show 2 or 3 IntroStepBuilder.

the Global Key is based on the order's value in IntroStepBuilder, make sure there's no IntroStepBuilder with the same order

**Comment by Hannnes1** [comment]
This issue appears when using different pages as well (at least with go_router). Is the idea to just increment the order even when navigating to a new page?

**Comment by yugin21** [comment]
> This issue appears when using different pages as well (at least with go_router). Is the idea to just increment the order even when navigating to a new page?

just use another/next number of order, it's not mandatory to start the Intro with number of order 0 or 1

**Comment by ShafiMunshi** [comment]
When using Intro on nested page always the next page order must be greater than the previous page
Apply order id in this way: 
page_1 -> page_2 -> page_3
1,2,3.................-> 101,102,103..........-> 201,202,203.........
