### ISSUE TITLE
I added a delay of 1200 milliseconds and executed Intro. of (context). start();, Result IntroButton（ onPressed: params.onNext, Text: 'Next step', ）This is not displayed

### ISSUE THREAD

**Issue by dary123** [minaxorg/flutter_intro#9]
I added a delay of 1200 milliseconds and executed Intro. of (context). start();, Result IntroButton（
onPressed: params.onNext,
Text: 'Next step',
）This is not displayed

**Comment by hellohejinyu** [comment]
Please check out the three sample projects of example for detailed usage methods.
